# Generated by Django 4.2.1 on 2023-10-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(blank=True, max_length=50, null=True)),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("domicilio", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso", models.IntegerField(blank=True, null=True)),
                (
                    "persona1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona1",
                        to="mainapp.persona",
                    ),
                ),
                (
                    "persona2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona2",
                        to="mainapp.persona",
                    ),
                ),
            ],
        ),
    ]
